### ISSUE TITLE
USE_1 : Login as employee

### ISSUE THREAD

**Issue by ograton** [SofteamOuest-Opus/user-mgmt#2]
(https://github.com/SofteamOuest-Opus/specs/blob/master/user-mgmt/software-design-description.adoc#scenario-s_1)

**Comment by yvzn** [comment]
duplicate of #6
duplicate of #7
duplicate of #8

**Comment by yvzn** [comment]
duplicate of #6

**Comment by yvzn** [comment]
duplicate of #7

**Comment by yvzn** [comment]
duplicate of #7
